### ISSUE TITLE
Not working with jetson xaiver jetpack 4.6?

### ISSUE THREAD

**Issue by toplinuxsir** [ceccocats/tkDNN#265]
not working with jetson xaiver jetpack 4.6?
compile error:
```
tkDNN/include/tkDNN/pluginsRT/ActivationLeakyRT.h(4): error: incomplete type is not allowed
```

**Comment by mive93** [comment]
Hi @toplinuxsir,
The problem is TensorRT8, it's still a WIP.

**Comment by toplinuxsir** [comment]
@mive93 Thanks I got it

**Comment by mive93** [comment]
TensorRT8 is now supported on [tensorrt8 branch](https://github.com/ceccocats/tkDNN/tree/tensorrt8).
Every model and data type is properly working.
